#!/usr/bin/env bash
# This script tells a story about each user from /etc/passwd using a while loop and IFS

while IFS=: read -r username password userid groupid userinfo home command; do
  echo "The user $username is part of the $groupid gang, lives in $home and rides $command."
  echo "User ID $userid's place is protected by the passcode $password, more info about the user here: $userinfo"
  echo "---------------------------------------------------------------"
done < /etc/passwd
