#!/usr/bin/env bash
# Display times from 00:01 to 12:59 using while loops

hour=0
while [ "$hour" -le 12 ]; do
  minute=1
  while [ "$minute" -le 59 ]; do
    printf '%02d:%02d\n' "$hour" "$minute"
    minute=$((minute + 1))
  done
  hour=$((hour + 1))
done
