#!/usr/bin/env bash
# 4-to_infinity_and_beyond: runs until stopped

flag="/tmp/4-to_infinity_and_beyond.flag"
echo "running" > "$flag"

while [ -f "$flag" ]; do
    echo "To infinity and beyond"
    sleep 1
done

echo "Terminated"
